// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/cache.proto

package cache

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_b53a136fb98cc91a, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_b53a136fb98cc91a, []int{1}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "cache.Item")
	proto.RegisterType((*Key)(nil), "cache.Key")
}

func init() { proto.RegisterFile("api/proto/cache.proto", fileDescriptor_b53a136fb98cc91a) }

var fileDescriptor_b53a136fb98cc91a = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x03, 0xb3, 0x85, 0x58,
	0xc1, 0x1c, 0x29, 0xe9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x88, 0x82, 0xa4, 0xd2, 0x34, 0xfd,
	0xd4, 0xdc, 0x82, 0x92, 0x4a, 0x88, 0x1a, 0x25, 0x3d, 0x2e, 0x16, 0xcf, 0x92, 0xd4, 0x5c, 0x21,
	0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48,
	0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x06, 0xe1, 0x28, 0x89, 0x73,
	0x31, 0x7b, 0xa7, 0x56, 0x62, 0x2a, 0x37, 0x6a, 0x64, 0xe4, 0x62, 0x75, 0x06, 0xd9, 0x27, 0x24,
	0xc7, 0xc5, 0xec, 0x9e, 0x5a, 0x22, 0xc4, 0xa5, 0x07, 0x71, 0x8b, 0x77, 0x6a, 0xa5, 0x14, 0x37,
	0x94, 0x0d, 0xb6, 0x4a, 0x8b, 0x8b, 0x39, 0x38, 0xb5, 0x44, 0x08, 0x59, 0x4c, 0x4a, 0x4c, 0x0f,
	0xe2, 0x48, 0x3d, 0x98, 0x23, 0xf5, 0x5c, 0x41, 0x8e, 0x14, 0xd2, 0xe1, 0x62, 0x73, 0x49, 0xcd,
	0x49, 0x2d, 0x49, 0x45, 0x31, 0x0e, 0x87, 0x6a, 0x27, 0x81, 0x28, 0x3e, 0xb8, 0x27, 0xc1, 0xaa,
	0x93, 0xd8, 0xc0, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xe1, 0x28, 0x8a, 0x22,
	0x01, 0x00, 0x00,
}
